presubmits:
  - name: test-node-tagger
    decorate: true
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/node-tagger.git"
    max_concurrency: 1
    trigger: "(?m)test( please)?"
    rerun_command: "test"
    spec:
      containers:
        - name: "test"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/go-builder:1.14.0
          command:
            - make
          args:
            - test
  - name: lint-node-tagger
    decorate: true
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/node-tagger.git"
    max_concurrency: 1
    trigger: "(?m)lint( please)?"
    rerun_command: "lint"
    spec:
      containers:
        - name: "lint"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/go-builder:1.14.0
          command:
            - make
          args:
            - lint
          resources:
            requests:
              memory: "2Gi"
              cpu: 1
  - name: helm-chart-lint-node-tagger
    context: helm-chart-lint-node-tagger
    decorate: true
    run_if_changed: 'deploy/helm/'
    always_run: false
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/node-tagger.git"
    max_concurrency: 1
    trigger: "(?m)helm-lint( please)?"
    rerun_command: "helm-lint"
    spec:
      containers:
        - name: "helm-chart-lint"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/helm:v3.1.1
          command:
            - make
          args:
            - helm-lint
  - name: helm-chart-validate-node-tagger
    context: helm-chart-validate-node-tagger
    decorate: true
    run_if_changed: 'deploy/helm/'
    always_run: false
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/node-tagger.git"
    max_concurrency: 1
    trigger: "(?m)helm-validate( please)?"
    rerun_command: "helm-validate"
    spec:
      containers:
        - name: "helm-chart-validate"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/helm:v3.1.1
          command:
            - make
          args:
            - helm-validate
  - name: helm-chart-package-node-tagger
    context: helm-chart-package-node-tagger
    decorate: true
    run_if_changed: 'deploy/helm/'
    always_run: false
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/node-tagger.git"
    max_concurrency: 1
    trigger: "(?m)helm-package( please)?"
    rerun_command: "helm-package"
    spec:
      containers:
        - name: "helm-chart-package"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/helm:v3.1.1
          command:
            - make
          args:
            - helm-package
            - VERSION=0.0.0
  - name: test-semrelease-dryrun-node-tagger
    context: test-semrelease-dryrun-node-tagger
    decorate: true
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/node-tagger.git"
    max_concurrency: 1
    labels:
      preset-semantic-release: "true"
    trigger: "(?m)semrelease-dryrun( please)?"
    rerun_command: "semrelease-dryrun"
    spec:
      containers:
        - name: "test-semrelease-dryrun"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/toolbox:0.1.17
          command:
            - make
          args:
            - semantic-release-dry-run
postsubmits:
  - name: node-tagger-release
    labels:
      preset-semantic-release: "true"
      preset-gcloud-testinfra-prow: "true"
    clone_uri: "git@github.com:ouzi-dev/node-tagger.git"
    decorate: true
    max_concurrency: 1
    branches:
      - master
    spec:
      nodeSelector:
        group_name: image-builder
      tolerations:
        - key: "imagebuilderonly"
          value: "true"
          operator: "Equal"
          effect: "PreferNoSchedule"
      containers:
        - name: "release"
          imagePullPolicy: Always
          image: quay.io/ouzi/toolbox:0.1.17
          command:
            - make
          args:
            - init-gcloud-cli
            - semantic-release
