kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-tagger
subjects:
- kind: ServiceAccount
  name: node-tagger
roleRef:
  kind: Role
  name: node-tagger
  apiGroup: rbac.authorization.k8s.io
